version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run tests and generate coverage report
          command: mvn clean test jacoco:report
      - store_test_results:
          path: target/surefire-reports
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml  # fichier de couverture

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-java

  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master