version: 2.1
orbs:
  codecov: codecov/codecov@3.2.5

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY

      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
          flags: unittest
          token: ${CODECOV_TOKEN}


  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build project
          command: mvn package

  publish-latest:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Publish latest version
          command: |
            echo "Publishing latest version"

workflows:
  version: 2
  upload-to-codecov:
    jobs:
      - test-java

  build-and-test:
    jobs:
      - test-java

  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master