version: 2.1
orbs:
  codecov: codecov/codecov@4.0.1
variables:
  CODECOV_TOKEN=cef5a71b-a066-4750-9b07-a447e399983c
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run tests
          command: mvn clean verify jacoco:report
      - store_test_results:
          path: target/surefire-reports

  codecov-upload:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Test
          command: mvn test
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -s target/site/jacoco.xml -r Benjamin-Berard/ceri-m1-techniques-de-test -v

  checkstyle:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Install Maven
          command: apt-get update && apt-get install -y maven
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build project
          command: mvn package

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-java
      - checkstyle

      - build:
          filters:
            branches:
              only: master
      - codecov-upload:
          requires:
            - test-java



