version: 2.1
orbs:
  codecov: codecov/codecov@4.0.1
variables:
  CODECOV_TOKEN=cef5a71b-a066-4750-9b07-a447e399983c
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run tests
          command: mvn clean verify jacoco:report
      - store_test_results:
          path: target/surefire-reports
      - codecov/upload:
          uses: codecov/codecov-action@v4
          with:
            verbose: true
          file: target/site/jacoco/jacoco.xml
          flags: unittest
          token: CODECOV_TOKEN
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}




  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build project
          command: mvn package

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-java
      - build:
          filters:
            branches:
              only: master
